no-tests = true
output = "models"
wipe = true

[mysql]
dbname = "DataPlatformMastersAndTransactionsMysqlKube"
host = "XXXXXXXXXXXXXX"
port = 30010
user = "XXXXXXXXXXXXXX"
pass = "XXXXXXXXXXXXXX"
sslmode = "false"
whitelist = ["data_platform_product_master_general_data"]
